### ISSUE TITLE
Allow to change mev-boost relays from Stakers UI

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1159]
Allow to change flashbots relays from Stakers UI:
- [ ] Set relay as env in the mev-boost packages:
  - [x] Mev-boost mainnet https://github.com/dappnode/DAppNodePackage-mev-boost/issues/12
  - [x] Mev-boost gnosis https://github.com/dappnode/DAppNodePackage-mev-boost-gnosis/issues/2
  - [x] Mev-boost prater  https://github.com/dappnode/DAppNodePackage-mev-boost-goerli/issues/7
- [ ] Define a hardcoded list of relays
- [ ] Allow to select the relay, either from the hardcoded list or a new one, to be set as an env in the mev-boost package
