### ISSUE TITLE
Add Lodestar Prater to StakersUI

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DNP_DAPPMANAGER#1194]
### Add Lodestar Prater to  Execution Clients
- [x] dappnode/DAppNodePackage-goerli-besu#14
- [x] dappnode/DAppNodePackage-goerli-erigon#12
- [x] dappnode/DAppNodePackage-goerli-geth#68
- [x] dappnode/DAppNodePackage-goerli-nethermind#18
### DAPPMANAGER and server-mock for all networks
- [x] dappnode/DNP_DAPPMANAGER#1203
### Web3Signer
- [x] dappnode/DAppNodePackage-web3signer-prater#68
- [x] dappnode/DAppNodePackage-web3signer-prater#71
### Other
- [x] dappnode/DAppNodePackage-SSV-Shifu#11
- [x] Test and Duplicate for mainnet when confirmed to be working.

**Comment by alexpeterson91** [comment]
@dapplion can yiu please take a look at this? I have linked PRs to every item listed here. Please confirm lodestar v0.1.2 stable is ready for the web3 signer. I arranged and prepped everything here just need your review since it's lodestar and there's no doubt you know it best.

**Comment by dapplion** [comment]
@alexpeterson91 Lodestar v1.2.0 is stable and ready for web3signer yes :+1: :tada: commit for reference https://github.com/ChainSafe/lodestar/commit/9254e72a046c934ed2b2e45abbf6ca3322fa4aa8

**Comment by alexpeterson91** [comment]
closed a while ago now,
