### ISSUE TITLE
TEST v0.2.39

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#653]
# Testing  [v0.2.39](https://github.com/dappnode/DNP_DAPPMANAGER/milestone/6)

## Core updates

| Core packages   |      Update    | version | Hash
|:-----------------------|:-----------------:|----------:|:---------:|
| [DNP_CORE](https://github.com/dappnode/DNP_CORE) | yes  | v0.2.43 | /ipfs/QmZd2tp9HShcJ8kdfHMtgYQaDUxEMgNV5Fx8puuQeL5eDP |
| [DNP_DAPPMANAGER](https://github.com/dappnode/DNP_DAPPMANAGER) | yes | v0.2.39 | /ipfs/QmZob1UdeEj5LetG334kyXFt2kPu8orpxqYtQYZFmBd5zg |
| [DNP_WIREGUARD](https://github.com/dappnode/DAppNodePackage-wireguard) | no | v0.1.0 |  |
| [DNP_HTTPS](https://github.com/dappnode/DAppNodePackage-https-portal) | yes | v0.1.0|/ipfs/QmcSwLvu5jmbK8vRvsuPovY9T6nhiJHJ7Ho1LpJgho3zEF |
| [DNP_VPN](https://github.com/dappnode/DNP_VPN) | no  |v0.2.8 |  |
| [DNP_IPFS](https://github.com/dappnode/DNP_IPFS) | no |v0.2.14 |  |
| [DNP_WIFI](https://github.com/dappnode/DNP_WIFI) | no | v0.2.6|  |
| [DNP_BIND](https://github.com/dappnode/DNP_BIND) | no |v0.2.6 |  |

## _General_ test

Test general functionalities of DAppNode 

- [x] Install/uninstall DAppNode package
- [x] Auto-updates
- [x] Connectivity
    - [x] VPN
    - [x] ssh
    - [x] wifi
- [x] UI
- [x] Reboot/shutdown
- [x] Backend
    - [x] Databases
    - [x] Daemons
- [x] Web browser compatibility
- [x] Architecture compatibility

## _New features_ test

Test new features implemented

- [x] Update check in dashboard: https://github.com/dappnode/DNP_DAPPMANAGER/pull/689
- [x] https portal: https://github.com/dappnode/DNP_DAPPMANAGER/issues/541
    - Comments: error view by default when HTTPS package is not installed :heavy_check_mark: :. Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/issues/700
- [x] Improve usability WEB3_HOST env: https://github.com/dappnode/DNP_DAPPMANAGER/issues/619
    - [x] Change variables at **packages > system packages > dappmanager > config**
    - [x] Set remote client
- [x] IPFS usage: https://github.com/dappnode/DNP_DAPPMANAGER/issues/474 
   - Comments: :warning:  It does not work properly, For the next release it will be fixed
- [x] Allow to declare networks in compose: https://github.com/dappnode/DNP_DAPPMANAGER/issues/591
    - [x] Create package with a custom network and install it
    - [x] Not allow custom network configuration
    - [x] Dappmanager sets default config to custom networks
    - [x] Check that network has been created after package uninstall
- [x] Events in UI fixed: https://github.com/dappnode/DNP_DAPPMANAGER/issues/583
    - [x] Check events works propertly
- [x] Allow to change hostname from UI: https://github.com/dappnode/DNP_DAPPMANAGER/issues/616
    - [x] Use the UI to change the hostname
    - [x] Check the hostname has changed
    - [x] UIX 
- [x] Script to collect host details
    - [x] Dappmanager should collect host details executing `collect_host_info.sh` on start
    - [x] In **support > report > system info** there should be displayed the docker version from the host instead of the dappmanager container
- [x] Clean DB functionality: https://github.com/dappnode/DNP_DAPPMANAGER/issues/445
    - [x] Clean db from UI
    - [x] Check has been cleaned in terminal
    - [x] Report if something critical happened
    - Comments: removes succesfully database, inmediately the UI  asks for introduce some settings again (set remote/full client, and change host password) :heavy_check_mark: 

## _Critical_ test

Major changes that might break some functionality. Must be tested in further detail.

- [x] Fix auto-updates: https://github.com/dappnode/DNP_DAPPMANAGER/pull/690
- [x] Docker script update: https://github.com/dappnode/DNP_DAPPMANAGER/issues/628
    - [x] Update docker engine from UI
    - [x] Update docker compose from UI
    - [x] Do random and big updates
    - [x] UIX
    - Comments: updated docker engine from 19 to 20.10.2 without issues. updated docker-compose from 1.12 to 1.15 without issues
- [x] Alias and network migration: https://github.com/dappnode/DNP_DAPPMANAGER/issues/625
    - [x] Composes files should have changed (core and non-core)
        - [x] Alias migration in compose and inspect
        - [x] Compose file version to `3.5`
        - [x] Network migration in compose and inspect: use of new feature **name** 
    - [x] Check logs/ipfs/QmTL65NzYsf7Fp5FgMd9AmBk1vEgDGDjbgmXayoxw1sgay
    - [x] Do fresh installation and verify `dncore_network` is created with prerrequisites script: `sudo wget -O - https://prerequisites.dappnode.io  | sudo bash` (deppends on https://github.com/dappnode/DAppNode_Installer/issues/100)
       - Comments: waiting for https://github.com/dappnode/DAppNode_Installer/pull/101
    - [x] Packages still work as expected
    - Comments:
       -  warning, `compose down` and then `compose up` might be critical for "networking packages" such as VPN and WIFI. FIXED: In those cases is executed `rm` followed by `compose-up` :warning:
       - `docker network disconnect` and `docker network connect` does not remove the previous configuration in the container when doing `docker inspect`, only adds new one :warning:
- [x] Support ports view: https://github.com/dappnode/DNP_DAPPMANAGER/issues/609
    - [x] UPnP and API scans
    - [x] UIX experience
    - [x] Mess around with API check-ports-service

## Test modes
- [x] [DNCORE_UPDATE](https://github.com/dappnode/DNP_CORE)
- [x] [ISO](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#how-to-install-dappnode-from-an-iso)
    - Comments: :warning: cannot execute `compose` against multiple composes files if compose file versions are different, fix with https://github.com/dappnode/DAppNode_Installer/pull/103 :heavy_check_mark: 
- [x] [Script](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#installation-via-installer-script)
- [x] VirtualBox
- [x] Future update

**Note** [This script](https://github.com/dappnode/DAppNode/blob/master/scripts/dappnode-new-realese.sh) may help to:
- Create DNP_CORE hash deppending on the core packages to be updated
- Create the ISO with the core packages new releases

## Testers

- @pablomendezroyo
- @tropicar
- @dapplion
