### ISSUE TITLE
Test V0.2.41

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#764]
# Testing  [v0.2.41](https://github.com/dappnode/DNP_DAPPMANAGER/milestone/6)

## Core updates

| Core packages   |      Update    | version | Hash
|:-----------------------|:-----------------:|----------:|:---------:|
| [DNP_CORE](https://github.com/dappnode/DNP_CORE) | yes  | v0.2.44 |  |
| [DNP_DAPPMANAGER](https://github.com/dappnode/DNP_DAPPMANAGER) | yes | v0.2.41 | /ipfs/QmcueaCTw8qDCfRTKefWmh5bkoCX4TkZwoWmkMM8CnfUSa  (commit 5648efc) |
| [DNP_WIREGUARD](https://github.com/dappnode/DAppNodePackage-wireguard) | core integration | v0.1.0 | /ipfs/QmUWzsbrCAyw7aAveQ4tCzuWD3yhAQBJNYMQ2gt1os8pd3 (commit  f5d580 ) |
| [DNP_HTTPS](https://github.com/dappnode/DAppNodePackage-https-portal) | yes | v0.1.1 | /ipfs/QmbC953gGmBT5yS2ATQWyYNxmy2wgrkbzAzT4ax8V9rdGT (commit da90e14) |
| [DNP_VPN](https://github.com/dappnode/DNP_VPN) | no  |v0.2.8 |  |
| [DNP_IPFS](https://github.com/dappnode/DNP_IPFS) | no |v0.2.14 |  |
| [DNP_WIFI](https://github.com/dappnode/DNP_WIFI) | yes | v0.2.7| /ipfs/QmZi96FxJZbf5o3bjDqkSnii1w8SpTRDd5JsqDsjrETzMo (commit daafa15 ) |
| [DNP_BIND](https://github.com/dappnode/DNP_BIND) | no |v0.2.6 |  |
| [DAppNode_Installer](https://github.com/dappnode/DAppNode_Installer) | yes | v0.2.44 | |

## _General_ test

Test general functionalities of DAppNode 

- [x] Install/uninstall DAppNode package
- [ ] Auto-updates
- [x] Connectivity
    - [x] VPN
       - [ ] Wireguard
       - [ ] Openvpn 
    - [x] ssh
    - [x] wifi
    - [x] Avahi
- [x] UI
- [x] Reboot/shutdown
- [x] Backend
    - [ ] Databases
    - [ ] Daemons
- [ ] Web browser compatibility
- [ ] Architecture compatibility

## _New features_ test

- [x] UIX:
  - [ ] Wi-Fi view: https://github.com/dappnode/DNP_DAPPMANAGER/pull/742
  - [x] VPN view: https://github.com/dappnode/DNP_DAPPMANAGER/pull/747
  - [x] Avahi control panel: https://github.com/dappnode/DNP_DAPPMANAGER/issues/761
  - [x] Community view: https://github.com/dappnode/DNP_DAPPMANAGER/pull/752
  - [x] Local Network Discovery (Avahi): https://github.com/dappnode/DNP_DAPPMANAGER/issues/761
  - [x] Review welcome.dappnode webpage
     - [ ] Add 
- [x] Check all connectivity methods from a user point of view (Avahi, Wi-Fi, VPN, wireguard)
    - [x] Wi-Fi: manually stop it and make sure it does not restart, reproduce situation to make wifi exit and make sure it restart by itself
        - [x] Stopping container rersults in error code 137 : https://github.com/dappnode/DNP_WIFI/issues/30
    - [x] Avahi: connect, start/stop it.
    - [x] Wireguard: 
        - [x] get remote and local credentials from cli: https://github.com/dappnode/DNP_WIREGUARD/pull/12
        - [ ] Connect with remote and local credentials
   
- [x] Check Wi-Fi is working as expected after last changes
- [x] Test UPnP scan: https://github.com/dappnode/DNP_DAPPMANAGER/pull/771
- [x] Test container aliases instead of IPs are working propertly: https://github.com/dappnode/DNP_DAPPMANAGER/issues/654
- [x] Security updates: https://github.com/dappnode/DNP_DAPPMANAGER/pull/748
- [ ] Reproduce HTTPs portal mapping issue and refresh https portal mapping with the button. Check result is as expected (mapping done again): https://github.com/dappnode/DNP_DAPPMANAGER/pull/770
- [ ] Docker update script logs: https://github.com/dappnode/DNP_DAPPMANAGER/pull/754
- [x] Installer: 
    - [x] deep test (ISO, scripts, unhattended, attended, versioning)
    - [ ] Test all commands available (check out the new ones)
    - [ ] Test CI implemented
    - [ ] Test script access_credentials.sh on startup

## Test modes
- [x] [DNCORE_UPDATE](https://github.com/dappnode/DNP_CORE)
- [x] [ISO](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#how-to-install-dappnode-from-an-iso)
- [x] [Script](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#installation-via-installer-script)
- [x] VirtualBox
- [ ] Future update

**Note** [This script](https://github.com/dappnode/DAppNode/blob/master/scripts/dappnode-new-realese.sh) may help to:
- Create DNP_CORE hash deppending on the core packages to be updated
- Create the ISO with the core packages new releases

## Testers

- @pablomendezroyo
- @tropicar
- @dapplion
- @3alpha 

=================================================================================================
### DAPPMANAGER
- Avahi:
  - Avahi-daemon should be installed on host: https://github.com/dappnode/DNP_DAPPMANAGER/issues/787
  - Avahi not working after avahi-publish command working
- HTTPS:
  - Port 443 not opened
- Update documentation endpoints: https://github.com/dappnode/DNP_DAPPMANAGER/issues/786
- Multiservice packages labels wrong assign dnpname: https://github.com/dappnode/DNP_DAPPMANAGER/issues/788

### INSTALLER
- `access_credentials.sh` script not working propertly: https://github.com/dappnode/DAppNode_Installer/issues/157
- Install avahi-daemon on host by default: https://github.com/dappnode/DAppNode_Installer/issues/156

**Comment by pablomendezroyo** [comment]
new release done
